.TH "RosAriaDriver_package.drive.RosAriaDriver" 3 "Pt, 13 mar 2015" "RosAriaDriver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RosAriaDriver_package.drive.RosAriaDriver \- 
Klasa ułatwiająca połączenie z robotem Pioneer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.RI "\fIKonstruktor\&. \fP"
.ti -1c
.RI "def \fBRotate\fP"
.br
.RI "\fIPowoduje obrót robota\&. \fP"
.ti -1c
.RI "def \fBGoTo\fP"
.br
.RI "\fIPowoduje jazdę robota\&. \fP"
.ti -1c
.RI "def \fBSetSpeed\fP"
.br
.RI "\fIZadanie prędkości jazdy i obrotu\&. \fP"
.ti -1c
.RI "def \fBSetSpeedLR\fP"
.br
.RI "\fIZadanie prędkości lewego i prawego koła \&. \fP"
.ti -1c
.RI "def \fBGripperOpen\fP"
.br
.RI "\fIOtwarcie chwytaka\&. \fP"
.ti -1c
.RI "def \fBGripperClose\fP"
.br
.RI "\fIZamknięcie chwytaka\&. \fP"
.ti -1c
.RI "def \fBGripperUp\fP"
.br
.RI "\fIPodniesienie chwytaka\&. \fP"
.ti -1c
.RI "def \fBGripperDown\fP"
.br
.RI "\fIOpuszczenie chwytaka\&. \fP"
.ti -1c
.RI "def \fBGetPose\fP"
.br
.RI "\fIMetoda zwracająca pozycje robota\&. \fP"
.ti -1c
.RI "def \fBResetPose\fP"
.br
.RI "\fIZeruje pozycję robota\&. \fP"
.ti -1c
.RI "def \fBReadSonar\fP"
.br
.RI "\fIZwraca dane z sonarów\&. \fP"
.ti -1c
.RI "def \fBAbout\fP"
.br
.RI "\fIInformacja\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa ułatwiająca połączenie z robotem Pioneer\&. 


.PP
\fBAutor:\fP
.RS 4
Damian Barański 
.br
 
.RE
.PP
\fBData:\fP
.RS 4
25/02/2015 
.br
 
.RE
.PP
\fBLicencja:\fP
.RS 4
Projekt rozwijany na licencji GNU GPL 
.RE
.PP

.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.__init__ (self, robot)"

.PP
Konstruktor\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.br
\fIrobot\fP Nazwa robota\&. 
.RE
.PP

.SH "Dokumentacja funkcji składowych"
.PP 
.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.About (self)"

.PP
Informacja\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GetPose (self)"

.PP
Metoda zwracająca pozycje robota\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
x[m], y[m], z[stopnie]\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GoTo (self, X)"

.PP
Powoduje jazdę robota\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.br
\fIX\fP Ilość metrów do przejechania\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GripperClose (self)"

.PP
Zamknięcie chwytaka\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GripperDown (self)"

.PP
Opuszczenie chwytaka\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GripperOpen (self)"

.PP
Otwarcie chwytaka\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.GripperUp (self)"

.PP
Podniesienie chwytaka\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.ReadSonar (self)"

.PP
Zwraca dane z sonarów\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP
\fBZwraca:\fP
.RS 4
tabicę [[x,y],[x,y],\&.\&.\&.]\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.ResetPose (self)"

.PP
Zeruje pozycję robota\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.Rotate (self, angle)"

.PP
Powoduje obrót robota\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.br
\fIangle\fP Kąt w którym ma się znaleźć robot\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.SetSpeed (self, X, Z, T)"

.PP
Zadanie prędkości jazdy i obrotu\&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.br
\fIX\fP Prędkość postępowa w [m/s]\&. 
.br
\fIZ\fP Prędkość obrotu w [rad/s]\&. 
.br
\fIT\fP Czas trwania w [s]\&. 
.RE
.PP

.SS "def RosAriaDriver_package\&.drive\&.RosAriaDriver\&.SetSpeedLR (self, L, R, T)"

.PP
Zadanie prędkości lewego i prawego koła \&. 
.PP
\fBParametry:\fP
.RS 4
\fIself\fP Wskaźnik na obiekt\&. 
.br
\fIL\fP Prędkość lewego koła w [m/s]\&. 
.br
\fIR\fP Prędkość prawego koła w[m/s]\&. 
.br
\fIT\fP Czas trwania w [s]\&. 
.RE
.PP


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla RosAriaDriver\&.
